/* AUTO-GENERATED by scripts/gen-network.mjs — network regions. */
export type Region = { name: string; color: string; icaos: string[] };

export const REGIONS: Region[] = [
  { name: "Finland", color: "#0C0243", icaos: ["EFTP","EFTU","EFJY","EFMA","EFVA","EFJO","EFKU","EFOU","EFKK","EFKI","EFKS","EFRO","EFKT","EFKE","EFIV"] },
  { name: "Baltics", color: "#3B6FE0", icaos: ["EETN","EETU","EVRA","EYVI"] },
  { name: "Scandinavia", color: "#12B5A8", icaos: ["ESSA","ESSV","ESGG","ENGM","ENVA","ENBR","ENBO","ENZV","ENTC","EKCH","EKBI","BIKF"] },
  { name: "Central Europe", color: "#8E5BFF", icaos: ["EPGD","EPWA","EPKK","EDDH","EDDB","EDDL","EDDM","EDDF","LKPR","LHBP","LOWW","LOWS","LOWI","LJLJ","LSZH","LSGG"] },
  { name: "Western Europe", color: "#2BA84A", icaos: ["EHAM","EBBR","LFPG","LFML","LFMN"] },
  { name: "British Isles", color: "#E2456A", icaos: ["EGPH","EGCC","EIDW","EGLL"] },
  { name: "Mediterranean", color: "#F2A33A", icaos: ["LIPZ","LIPX","LIPE","LIMC","LIRQ","LIRF","LIRN","LICC","LDSP","LDDU","LATI","LGAV","LGSR","LGSA","LGKO","LGRP","LGIR","LTAI","LTFG","LCLK"] },
  { name: "Iberia & Atlantic", color: "#00A0B0", icaos: ["LEBL","LEPA","LEVC","LEAL","LEMD","LEMG","LPPT","LPFR","LPMA","GCRR","GCXO","GCTS","GCLP"] },
  { name: "Middle East", color: "#C77D2E", icaos: ["OMDB","OTHH"] },
  { name: "Asia", color: "#E0529C", icaos: ["VIDP","ZSPD","VHHH","VTBS","VTSP","WSSS","RJBB","RKSI","RJGG","RJAA","RJTT","YMML"] },
  { name: "North America", color: "#5B6CFF", icaos: ["CYYZ","KJFK","KORD","KSEA","KDFW","KMIA","KLAX","MUHA","MDPC"] },
];

const ICAO_REGION = new Map<string, Region>();
for (const r of REGIONS) for (const i of r.icaos) ICAO_REGION.set(i, r);

export function regionForIcao(icao: string): Region | null { return ICAO_REGION.get(icao) ?? null; }
export function regionName(icao: string): string { return ICAO_REGION.get(icao)?.name ?? "—"; }
export function regionColor(icao: string): string { return ICAO_REGION.get(icao)?.color ?? "#0C0243"; }
