/* AUTO-GENERATED by scripts/gen-network.mjs — official FNVA route database.
   112 destinations from Helsinki-Vantaa (EFHK). */

export type Route = { routeNumber: string; dep: string; arr: string; aircraft: string; minutes: number; airline: string };

export const ROUTES: Route[] = [
  {
    "routeNumber": "AY1011/AY1012",
    "dep": "EFHK",
    "arr": "EETN",
    "aircraft": "A319 / E190",
    "minutes": 35,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY269/AY270",
    "dep": "EFHK",
    "arr": "EFTP",
    "aircraft": "A319",
    "minutes": 35,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY223/AY224",
    "dep": "EFHK",
    "arr": "EFTU",
    "aircraft": "A319",
    "minutes": 35,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1045/AY1047",
    "dep": "EFHK",
    "arr": "EETU",
    "aircraft": "A319",
    "minutes": 45,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY281/AY282",
    "dep": "EFHK",
    "arr": "EFJY",
    "aircraft": "A319",
    "minutes": 50,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY213/AY214",
    "dep": "EFHK",
    "arr": "EFMA",
    "aircraft": "A319",
    "minutes": 50,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY311/AY322",
    "dep": "EFHK",
    "arr": "EFVA",
    "aircraft": "A319",
    "minutes": 50,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY341/AY342",
    "dep": "EFHK",
    "arr": "EFJO",
    "aircraft": "A319",
    "minutes": 60,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY370/AY362",
    "dep": "EFHK",
    "arr": "EFKU",
    "aircraft": "A319 / E190",
    "minutes": 60,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1071/AY1072",
    "dep": "EFHK",
    "arr": "EVRA",
    "aircraft": "A319 / E190",
    "minutes": 60,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY801/AY802",
    "dep": "EFHK",
    "arr": "ESSA",
    "aircraft": "E190 / A321 / A320",
    "minutes": 60,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY433/AY434",
    "dep": "EFHK",
    "arr": "EFOU",
    "aircraft": "A320 / A321 / E190",
    "minutes": 65,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY393/AY394",
    "dep": "EFHK",
    "arr": "EFKK",
    "aircraft": "A319",
    "minutes": 70,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY415/AY416",
    "dep": "EFHK",
    "arr": "EFKI",
    "aircraft": "A319",
    "minutes": 75,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY481/AY482",
    "dep": "EFHK",
    "arr": "EFKS",
    "aircraft": "A320 / A321 / E190",
    "minutes": 75,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1101/AY1102",
    "dep": "EFHK",
    "arr": "EYVI",
    "aircraft": "E190 / A319",
    "minutes": 75,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY881/AY882",
    "dep": "EFHK",
    "arr": "ESSV",
    "aircraft": "A319",
    "minutes": 75,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY531/AY532",
    "dep": "EFHK",
    "arr": "EFRO",
    "aircraft": "A320 / A321 / A330",
    "minutes": 80,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY671/AY672",
    "dep": "EFHK",
    "arr": "ESGG",
    "aircraft": "E190",
    "minutes": 85,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY557/AY558",
    "dep": "EFHK",
    "arr": "EFKT",
    "aircraft": "A320 / A321",
    "minutes": 85,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY581/AY582",
    "dep": "EFHK",
    "arr": "EFKE",
    "aircraft": "A319",
    "minutes": 90,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY913/AY914",
    "dep": "EFHK",
    "arr": "ENGM",
    "aircraft": "A320 / A321 / E190",
    "minutes": 90,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1171/AY1172",
    "dep": "EFHK",
    "arr": "EPGD",
    "aircraft": "E190",
    "minutes": 95,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY611/AY612",
    "dep": "EFHK",
    "arr": "EFIV",
    "aircraft": "A319 / A320",
    "minutes": 95,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY961/AY962",
    "dep": "EFHK",
    "arr": "EKCH",
    "aircraft": "A320 / A321 / E190",
    "minutes": 100,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY923/AY924",
    "dep": "EFHK",
    "arr": "ENVA",
    "aircraft": "E190",
    "minutes": 100,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1148/AY1142",
    "dep": "EFHK",
    "arr": "EPWA",
    "aircraft": "E190",
    "minutes": 105,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY921/AY922",
    "dep": "EFHK",
    "arr": "ENBR",
    "aircraft": "A319 / E190",
    "minutes": 110,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY931/AY932",
    "dep": "EFHK",
    "arr": "ENBO",
    "aircraft": "E190",
    "minutes": 115,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1421/AY1422",
    "dep": "EFHK",
    "arr": "EDDH",
    "aircraft": "A320 / A321 / E190",
    "minutes": 115,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY921/AY922",
    "dep": "EFHK",
    "arr": "ENZV",
    "aircraft": "E190",
    "minutes": 115,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY946/AY947",
    "dep": "EFHK",
    "arr": "ENTC",
    "aircraft": "A319 / E190",
    "minutes": 115,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1161/AY1162",
    "dep": "EFHK",
    "arr": "EPKK",
    "aircraft": "E190",
    "minutes": 120,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1431/AY1432",
    "dep": "EFHK",
    "arr": "EDDB",
    "aircraft": "E190 / A320 / A321",
    "minutes": 125,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY5861/AY5862",
    "dep": "EFHK",
    "arr": "EKBI",
    "aircraft": "E190",
    "minutes": 130,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1223/AY1224",
    "dep": "EFHK",
    "arr": "LKPR",
    "aircraft": "A320 / A321 / E190",
    "minutes": 135,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1255/AY1256",
    "dep": "EFHK",
    "arr": "LHBP",
    "aircraft": "A320 / A321 / E190",
    "minutes": 140,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1391/AY1392",
    "dep": "EFHK",
    "arr": "EDDL",
    "aircraft": "A320 / A321 / E190",
    "minutes": 145,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1471/AY1472",
    "dep": "EFHK",
    "arr": "LOWW",
    "aircraft": "A320 / A321 / E190",
    "minutes": 150,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1301/AY1302",
    "dep": "EFHK",
    "arr": "EHAM",
    "aircraft": "A320 / A321",
    "minutes": 155,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1401/AY1402",
    "dep": "EFHK",
    "arr": "EDDM",
    "aircraft": "A320 / A321",
    "minutes": 155,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1501/AY1502",
    "dep": "EFHK",
    "arr": "LOWS",
    "aircraft": "A320 / A321",
    "minutes": 155,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1545/AY1546",
    "dep": "EFHK",
    "arr": "EBBR",
    "aircraft": "A320 / A321 / E190",
    "minutes": 160,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1411/AY1412",
    "dep": "EFHK",
    "arr": "EDDF",
    "aircraft": "A320 / A321",
    "minutes": 160,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1201/AY1202",
    "dep": "EFHK",
    "arr": "LJLJ",
    "aircraft": "A321",
    "minutes": 160,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1373/AY1376",
    "dep": "EFHK",
    "arr": "EGPH",
    "aircraft": "A320 / A321 / E190",
    "minutes": 165,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1491/AY1492",
    "dep": "EFHK",
    "arr": "LOWI",
    "aircraft": "A320 / A321",
    "minutes": 165,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1511/AY1512",
    "dep": "EFHK",
    "arr": "LSZH",
    "aircraft": "A320 / A321 / E190",
    "minutes": 170,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1781/AY1782",
    "dep": "EFHK",
    "arr": "LIPZ",
    "aircraft": "A320 / A321",
    "minutes": 175,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1801/AY1802",
    "dep": "EFHK",
    "arr": "LIPX",
    "aircraft": "A320 / A321",
    "minutes": 175,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1771/AY1772",
    "dep": "EFHK",
    "arr": "LIPE",
    "aircraft": "A320 / A321",
    "minutes": 180,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1531/AY1532",
    "dep": "EFHK",
    "arr": "LSGG",
    "aircraft": "A320 / A321",
    "minutes": 180,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1361/AY1362",
    "dep": "EFHK",
    "arr": "EGCC",
    "aircraft": "A320 / A321",
    "minutes": 180,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1821/AY1822",
    "dep": "EFHK",
    "arr": "LDSP",
    "aircraft": "A320 / A321",
    "minutes": 180,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1831/AY1832",
    "dep": "EFHK",
    "arr": "LDDU",
    "aircraft": "A320 / A321",
    "minutes": 185,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1751/AY1752",
    "dep": "EFHK",
    "arr": "LIMC",
    "aircraft": "A320 / A321",
    "minutes": 185,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1575/AY1576",
    "dep": "EFHK",
    "arr": "LFPG",
    "aircraft": "A320 / A321",
    "minutes": 185,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1381/AY1382",
    "dep": "EFHK",
    "arr": "EIDW",
    "aircraft": "A320 / A321 / E190",
    "minutes": 190,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1331/AY1332",
    "dep": "EFHK",
    "arr": "EGLL",
    "aircraft": "A350 / A330 / A320 / A321",
    "minutes": 190,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1813/AY1814",
    "dep": "EFHK",
    "arr": "LIRQ",
    "aircraft": "E190",
    "minutes": 195,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY371/AY372",
    "dep": "EFHK",
    "arr": "LFML",
    "aircraft": "A320",
    "minutes": 200,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1601/AY1602",
    "dep": "EFHK",
    "arr": "LFMN",
    "aircraft": "A320 / A321",
    "minutes": 205,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1761/AY1762",
    "dep": "EFHK",
    "arr": "LIRF",
    "aircraft": "A320 / A321",
    "minutes": 205,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1847/AY1848",
    "dep": "EFHK",
    "arr": "LATI",
    "aircraft": "A320",
    "minutes": 205,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1791/AY1792",
    "dep": "EFHK",
    "arr": "LIRN",
    "aircraft": "A320 / A321",
    "minutes": 210,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY991/AY992",
    "dep": "EFHK",
    "arr": "BIKF",
    "aircraft": "A320 / A321",
    "minutes": 210,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY2750/AY2752",
    "dep": "EFHK",
    "arr": "LGAV",
    "aircraft": "A320",
    "minutes": 220,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1951/AY1952",
    "dep": "EFHK",
    "arr": "LTAI",
    "aircraft": "A320 / A321",
    "minutes": 230,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1805/AY1806",
    "dep": "EFHK",
    "arr": "LICC",
    "aircraft": "A320 / A321",
    "minutes": 230,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1895/AY1896",
    "dep": "EFHK",
    "arr": "LGSR",
    "aircraft": "A320 / A321",
    "minutes": 230,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY5385/AY1652",
    "dep": "EFHK",
    "arr": "LEBL",
    "aircraft": "A320 / A321",
    "minutes": 235,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1859/AY1860",
    "dep": "EFHK",
    "arr": "LGSA",
    "aircraft": "A320 / A321",
    "minutes": 235,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1879/AY1880",
    "dep": "EFHK",
    "arr": "LGKO",
    "aircraft": "A320 / A321",
    "minutes": 235,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1863/AY1864",
    "dep": "EFHK",
    "arr": "LGRP",
    "aircraft": "A321",
    "minutes": 235,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1955/AY1956",
    "dep": "EFHK",
    "arr": "LTFG",
    "aircraft": "A320 / A321",
    "minutes": 240,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1885/AY1886",
    "dep": "EFHK",
    "arr": "LGIR",
    "aircraft": "A320 / A321",
    "minutes": 240,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1691/AY1692",
    "dep": "EFHK",
    "arr": "LEPA",
    "aircraft": "A320 / A321",
    "minutes": 240,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1681/AY1682",
    "dep": "EFHK",
    "arr": "LEVC",
    "aircraft": "A320 / A321",
    "minutes": 250,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1671/AY1672",
    "dep": "EFHK",
    "arr": "LEAL",
    "aircraft": "A320 / A321",
    "minutes": 260,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY5389/AY5390",
    "dep": "EFHK",
    "arr": "LEMD",
    "aircraft": "A320 / A321",
    "minutes": 265,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1673/AY1674",
    "dep": "EFHK",
    "arr": "LEMG",
    "aircraft": "A320 / A321",
    "minutes": 275,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1929/AY1930",
    "dep": "EFHK",
    "arr": "LCLK",
    "aircraft": "A320 / A321",
    "minutes": 275,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY4395/AY4396",
    "dep": "EFHK",
    "arr": "LPPT",
    "aircraft": "A320 / A321",
    "minutes": 290,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1741/AY1742",
    "dep": "EFHK",
    "arr": "LPFR",
    "aircraft": "A320 / A321",
    "minutes": 300,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1731/AY1732",
    "dep": "EFHK",
    "arr": "LPMA",
    "aircraft": "A320 / A321",
    "minutes": 345,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1711/AY1712",
    "dep": "EFHK",
    "arr": "GCRR",
    "aircraft": "A330-300",
    "minutes": 365,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1693/AY1694",
    "dep": "EFHK",
    "arr": "GCXO",
    "aircraft": "A330-300",
    "minutes": 365,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1961/AY1962",
    "dep": "EFHK",
    "arr": "OMDB",
    "aircraft": "A330-300",
    "minutes": 370,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1695/AY1696",
    "dep": "EFHK",
    "arr": "GCTS",
    "aircraft": "A330-300",
    "minutes": 370,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1981/AY1982",
    "dep": "EFHK",
    "arr": "OTHH",
    "aircraft": "A330-300",
    "minutes": 375,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1701/AY1702",
    "dep": "EFHK",
    "arr": "GCLP",
    "aircraft": "A330-300",
    "minutes": 375,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY121/AY122",
    "dep": "EFHK",
    "arr": "VIDP",
    "aircraft": "A350-900",
    "minutes": 440,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY31/AY32",
    "dep": "EFHK",
    "arr": "CYYZ",
    "aircraft": "A330-300 / A350-900",
    "minutes": 510,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY15/AY16",
    "dep": "EFHK",
    "arr": "KJFK",
    "aircraft": "A330-300 / A350-900",
    "minutes": 525,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY09/AY10",
    "dep": "EFHK",
    "arr": "KORD",
    "aircraft": "A330-300",
    "minutes": 555,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY33/AY34",
    "dep": "EFHK",
    "arr": "KSEA",
    "aircraft": "A330-300",
    "minutes": 585,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY87/AY88",
    "dep": "EFHK",
    "arr": "ZSPD",
    "aircraft": "A350-900",
    "minutes": 615,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY19/AY20",
    "dep": "EFHK",
    "arr": "KDFW",
    "aircraft": "A350-900",
    "minutes": 630,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY99/AY100",
    "dep": "EFHK",
    "arr": "VHHH",
    "aircraft": "A350-900",
    "minutes": 635,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY28/AY28",
    "dep": "EFHK",
    "arr": "MUHA",
    "aircraft": "A350-900",
    "minutes": 650,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY7/AY8",
    "dep": "EFHK",
    "arr": "KMIA",
    "aircraft": "A350-900",
    "minutes": 650,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY23/AY24",
    "dep": "EFHK",
    "arr": "MDPC",
    "aircraft": "A350-900",
    "minutes": 670,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY01/AY02",
    "dep": "EFHK",
    "arr": "KLAX",
    "aircraft": "A350-900",
    "minutes": 675,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY141/AY142",
    "dep": "EFHK",
    "arr": "VTBS",
    "aircraft": "A350-900",
    "minutes": 685,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY151/AY152",
    "dep": "EFHK",
    "arr": "VTSP",
    "aircraft": "A350-900",
    "minutes": 710,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY131/AY132",
    "dep": "EFHK",
    "arr": "WSSS",
    "aircraft": "A350-900",
    "minutes": 720,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY69/AY70",
    "dep": "EFHK",
    "arr": "RJBB",
    "aircraft": "A350-900",
    "minutes": 780,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY41/AY42",
    "dep": "EFHK",
    "arr": "RKSI",
    "aircraft": "A350-900",
    "minutes": 780,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY79/AY80",
    "dep": "EFHK",
    "arr": "RJGG",
    "aircraft": "A350-900",
    "minutes": 790,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY73/AY74",
    "dep": "EFHK",
    "arr": "RJAA",
    "aircraft": "A350-900",
    "minutes": 795,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY61/AY62",
    "dep": "EFHK",
    "arr": "RJTT",
    "aircraft": "A350-900",
    "minutes": 810,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY145/AY146",
    "dep": "EFHK",
    "arr": "YMML",
    "aircraft": "A350-900",
    "minutes": 1290,
    "airline": "Finnair"
  }
];

export const ROUTE_AIRLINES = ["Finnair"] as const;
