/* AUTO-GENERATED by scripts/gen-finnair-routes.mjs — Finnair Virtual route
   network, anchored at Helsinki-Vantaa (EFHK). Mainline flights wear the AY
   code; codeshare legs carry the partner's flight number and airline. */

export type Route = {
  routeNumber: string;
  dep: string;
  arr: string;
  aircraft: string;
  minutes: number;
  airline: string;
};

export const ROUTES: Route[] = [
  {
    "routeNumber": "AY531/AY532",
    "dep": "EFHK",
    "arr": "EFRO",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 80,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY433/AY434",
    "dep": "EFHK",
    "arr": "EFOU",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 60,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY631/AY632",
    "dep": "EFHK",
    "arr": "EFKT",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 95,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY641/AY642",
    "dep": "EFHK",
    "arr": "EFIV",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 100,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY343/AY344",
    "dep": "EFHK",
    "arr": "EFVA",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 50,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY811/AY812",
    "dep": "EFHK",
    "arr": "ESSA",
    "aircraft": "Finnair Airbus A320",
    "minutes": 60,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY661/AY662",
    "dep": "EFHK",
    "arr": "EKCH",
    "aircraft": "Finnair Airbus A320",
    "minutes": 95,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY915/AY916",
    "dep": "EFHK",
    "arr": "ENGM",
    "aircraft": "Finnair Airbus A320",
    "minutes": 95,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1011/AY1012",
    "dep": "EFHK",
    "arr": "EETN",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 35,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1701/AY1702",
    "dep": "EFHK",
    "arr": "EVRA",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 65,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1141/AY1142",
    "dep": "EFHK",
    "arr": "EYVI",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 80,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1059/AY1060",
    "dep": "EFHK",
    "arr": "ESGG",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 75,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1331/AY1332",
    "dep": "EFHK",
    "arr": "EGLL",
    "aircraft": "Finnair Airbus A321",
    "minutes": 170,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY871/AY872",
    "dep": "EFHK",
    "arr": "LFPG",
    "aircraft": "Finnair Airbus A321",
    "minutes": 195,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY841/AY842",
    "dep": "EFHK",
    "arr": "EDDF",
    "aircraft": "Finnair Airbus A321",
    "minutes": 165,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1401/AY1402",
    "dep": "EFHK",
    "arr": "EHAM",
    "aircraft": "Finnair Airbus A320",
    "minutes": 170,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1561/AY1562",
    "dep": "EFHK",
    "arr": "LSZH",
    "aircraft": "Finnair Airbus A320",
    "minutes": 185,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1465/AY1466",
    "dep": "EFHK",
    "arr": "LOWW",
    "aircraft": "Finnair Airbus A320",
    "minutes": 165,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1381/AY1382",
    "dep": "EFHK",
    "arr": "EIDW",
    "aircraft": "Finnair Airbus A320",
    "minutes": 195,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1153/AY1154",
    "dep": "EFHK",
    "arr": "EPWA",
    "aircraft": "Nordic Regional Embraer 190",
    "minutes": 95,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1733/AY1734",
    "dep": "EFHK",
    "arr": "EDDM",
    "aircraft": "Finnair Airbus A320",
    "minutes": 165,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1623/AY1624",
    "dep": "EFHK",
    "arr": "EBBR",
    "aircraft": "Finnair Airbus A320",
    "minutes": 160,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1851/AY1852",
    "dep": "EFHK",
    "arr": "LEBL",
    "aircraft": "Finnair Airbus A321",
    "minutes": 240,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY3271/AY3272",
    "dep": "EFHK",
    "arr": "LEMD",
    "aircraft": "Finnair Airbus A321",
    "minutes": 255,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1761/AY1762",
    "dep": "EFHK",
    "arr": "LIRF",
    "aircraft": "Finnair Airbus A321",
    "minutes": 230,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1721/AY1722",
    "dep": "EFHK",
    "arr": "LGAV",
    "aircraft": "Finnair Airbus A321",
    "minutes": 230,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1571/AY1572",
    "dep": "EFHK",
    "arr": "LFMN",
    "aircraft": "Finnair Airbus A320",
    "minutes": 215,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1931/AY1932",
    "dep": "EFHK",
    "arr": "LPPT",
    "aircraft": "Finnair Airbus A321",
    "minutes": 290,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY15/AY16",
    "dep": "EFHK",
    "arr": "KJFK",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 545,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY11/AY12",
    "dep": "EFHK",
    "arr": "KORD",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 555,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY1/AY2",
    "dep": "EFHK",
    "arr": "KLAX",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 660,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY3/AY4",
    "dep": "EFHK",
    "arr": "KSFO",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 645,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY21/AY22",
    "dep": "EFHK",
    "arr": "KSEA",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 585,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY119/AY120",
    "dep": "EFHK",
    "arr": "KMIA",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 615,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY113/AY114",
    "dep": "EFHK",
    "arr": "KDFW",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 615,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY73/AY74",
    "dep": "EFHK",
    "arr": "RJTT",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 575,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY41/AY42",
    "dep": "EFHK",
    "arr": "RKSI",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 555,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY57/AY58",
    "dep": "EFHK",
    "arr": "ZSPD",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 565,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY101/AY102",
    "dep": "EFHK",
    "arr": "VHHH",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 600,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY133/AY134",
    "dep": "EFHK",
    "arr": "WSSS",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 660,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY81/AY82",
    "dep": "EFHK",
    "arr": "RPLL",
    "aircraft": "Finnair Airbus A350-900",
    "minutes": 690,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY141/AY142",
    "dep": "EFHK",
    "arr": "VTBS",
    "aircraft": "Finnair Airbus A330-300",
    "minutes": 615,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY121/AY122",
    "dep": "EFHK",
    "arr": "VABB",
    "aircraft": "Finnair Airbus A330-300",
    "minutes": 540,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY123/AY124",
    "dep": "EFHK",
    "arr": "VIDP",
    "aircraft": "Finnair Airbus A330-300",
    "minutes": 510,
    "airline": "Finnair"
  },
  {
    "routeNumber": "AY131/AY132",
    "dep": "EFHK",
    "arr": "OMDB",
    "aircraft": "Finnair Airbus A330-300",
    "minutes": 390,
    "airline": "Finnair"
  },
  {
    "routeNumber": "BA793/BA794",
    "dep": "EFHK",
    "arr": "EGLL",
    "aircraft": "British Airways Boeing 787-8",
    "minutes": 175,
    "airline": "British Airways"
  },
  {
    "routeNumber": "BA117/BA118",
    "dep": "EGLL",
    "arr": "KJFK",
    "aircraft": "British Airways Boeing 777-300ER",
    "minutes": 460,
    "airline": "British Airways"
  },
  {
    "routeNumber": "IB3445/IB3446",
    "dep": "EFHK",
    "arr": "LEMD",
    "aircraft": "Iberia Airbus A321",
    "minutes": 270,
    "airline": "Iberia"
  },
  {
    "routeNumber": "EI341/EI342",
    "dep": "EFHK",
    "arr": "EIDW",
    "aircraft": "Aer Lingus Airbus A320",
    "minutes": 200,
    "airline": "Aer Lingus"
  },
  {
    "routeNumber": "SK706/SK707",
    "dep": "EFHK",
    "arr": "ESSA",
    "aircraft": "SAS Airbus A320neo",
    "minutes": 60,
    "airline": "SAS"
  },
  {
    "routeNumber": "QR306/QR307",
    "dep": "EFHK",
    "arr": "OTHH",
    "aircraft": "Qatari Boeing 787-8",
    "minutes": 380,
    "airline": "Qatari"
  },
  {
    "routeNumber": "QR707/QR708",
    "dep": "OTHH",
    "arr": "WSSS",
    "aircraft": "Qatari Airbus A350-1000",
    "minutes": 460,
    "airline": "Qatari"
  },
  {
    "routeNumber": "JL414/JL413",
    "dep": "EFHK",
    "arr": "RJTT",
    "aircraft": "Japan Airlines Boeing 787-9",
    "minutes": 580,
    "airline": "Japan Airlines"
  },
  {
    "routeNumber": "JL58/JL57",
    "dep": "RJTT",
    "arr": "KSFO",
    "aircraft": "Japan Airlines Boeing 777-300ER",
    "minutes": 575,
    "airline": "Japan Airlines"
  },
  {
    "routeNumber": "CX101/CX100",
    "dep": "VHHH",
    "arr": "YSSY",
    "aircraft": "Cathay Boeing 777-300ER",
    "minutes": 555,
    "airline": "Cathay"
  },
  {
    "routeNumber": "QF1/QF2",
    "dep": "YSSY",
    "arr": "EGLL",
    "aircraft": "Qantas Airbus A380",
    "minutes": 1380,
    "airline": "Qantas"
  },
  {
    "routeNumber": "MH1/MH2",
    "dep": "WMKK",
    "arr": "EGLL",
    "aircraft": "Malaysia Airlines Airbus A350-900",
    "minutes": 820,
    "airline": "Malaysia Airlines"
  },
  {
    "routeNumber": "AA2400/AA2401",
    "dep": "KJFK",
    "arr": "KDFW",
    "aircraft": "American Airlines Boeing 737 MAX 8",
    "minutes": 240,
    "airline": "American"
  }
];

/* Distinct airlines for the route-browser filter (mainline first). */
export const ROUTE_AIRLINES = ["Finnair","British Airways","Iberia","Aer Lingus","SAS","Qatari","Japan Airlines","Cathay","Qantas","Malaysia Airlines","American"] as const;
